language: minimal

jobs:
  include:
    - stage: run tests and build docker image
      script:
        # set bash flag to fail immediately for any command
        - set -e
        # derive the docker image tag name from the git branch name
        - if [[ $TRAVIS_BRANCH == 'master' ]]; then tag='latest'; else tag="$TRAVIS_BRANCH"; fi
        # build image
        - docker build -t flackdl/cwwed:$tag .
        # run postgis in the background
        - docker run --rm -d -p 5432:5432 mdillon/postgis
        # run tests
        - docker run --entrypoint python flackdl/cwwed:$tag manage.py test
        # authenticate with docker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # push to docker hub
        - docker push flackdl/cwwed:$tag
