#dist: xenial
language: python
python:
  - "3.6"
#install:
#  - pip install -r requirements.txt
#script:
#  - python manage.py test

jobs:
  include:
    - stage: build docker image
      script:
      # derive the docker image tag name from the git branch name
      - if [[ $TRAVIS_BRANCH == 'master' ]]; then tag='latest'; else tag="$TRAVIS_BRANCH"; fi
      # build image
      - docker build -t flackdl/cwwed:$tag .
      # authenticate with docker
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # push to docker hub
      - docker push flackdl/cwwed:$tag
