version: '2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    environment:
      - DJANGO_SETTINGS_MODULE=cwwed.settings-dev
    ports:
      - "9000:80"
    volumes:
      - .:/app
    depends_on:
      - db
