version: '2'

services:

  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - cwwed-postgresql:/var/lib/postgresql/data

  thredds:
    image: unidata/thredds-docker:4.6.11
    ports:
      - "9000:8080"
    container_name: thredds
    volumes:
      - ./configs/thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./configs/thredds/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - /media/bucket/cwwed:/usr/local/tomcat/content/thredds/public:ro
    env_file:
      - "compose.thredds.env"

volumes:
  cwwed-postgresql:
