version: '2'

services:

  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - cwwed-postgresql:/var/lib/postgresql/data

  opendap:
    image: opendap/hyrax:1.15.2
    ports:
      - "9000:8080"
    container_name: opendap
    volumes:
      - /media/bucket/cwwed/OPENDAP/:/usr/share/hyrax

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"

  #cwwed:
  #  build:
  #    context: .
  #  ports:
  #    - "8888:80"
  #  env_file: .env  # not in version control
  #  environment:
  #    DJANGO_SETTINGS_MODULE: cwwed.settings
  #    DATABASE_URL: postgis://postgres@postgis:5432/postgres
  #  depends_on:
  #    - postgis
  #    - opendap
  #    - rabbitmq

volumes:
  cwwed-postgresql:
