version: '2'

services:

  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - cwwed-postgresql:/var/lib/postgresql/data

  thredds:
    image: unidata/thredds-docker:4.6.11
    ports:
      - "9000:8080"
    container_name: thredds
    volumes:
      - ./configs/thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./configs/thredds/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - /media/bucket/cwwed:/usr/local/tomcat/content/thredds/public:ro
    env_file:
      - "compose.thredds.env"

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: celery -A cwwed worker -l info
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: celery flower -A cwwed --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - celery-worker

volumes:
  cwwed-postgresql:
