version: '2'

services:

  postgis:
    # version should match the server's
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    volumes:
      - cwwed-postgresql:/var/lib/postgresql/data

  opendap:
    image: opendap/hyrax:1.15.2
    ports:
      - "9000:8080"
    container_name: opendap
    volumes:
      - /media/bucket/cwwed/OPENDAP/:/usr/share/hyrax

  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  cwwed-postgresql:
