---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com

# NOTE: enter a volume & claim for each instance/deployment of CWWED (alpha, dev, prod etc)

---
# ALPHA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-alpha
spec:
  capacity:
    storage: 5Gi  # arbitrary
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-8c80050d:/alpha  # NOTE: enter file system ID / deployment

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-alpha
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi  # arbitrary

---
# DEV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-dev
spec:
  capacity:
    storage: 5Gi  # arbitrary
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-8c80050d:/dev  # NOTE: enter file system ID / deployment

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi  # arbitrary

---
