apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwwed-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cwwed-container
  template:
    metadata:
      labels:
        app: cwwed-container
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: cwwed-volume-claim
      containers:
      - name: cwwed-container
        image: cwwed-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings_aws
          - name: AWS_STORAGE_BUCKET_NAME
            value: cwwed-static-assets
          # secrets
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: DATABASE_URL
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SLACK_BOT_TOKEN
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SECRET_KEY
          - name: CWWED_NSEM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CWWED_NSEM_PASSWORD
