apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendap-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendap-container
  template:
    metadata:
      labels:
        app: opendap-container
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
        # minikube
        #claimName: cwwed-volume-claim
         claimName: efs
      containers:
      - name: opendap-container
        image: opendap/hyrax:1.15.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/usr/share/hyrax"
          name: cwwed-volume-storage
          subPath: OPENDAP
          readOnly: true
        resources:
          requests:
            memory: "1000M"
