!Defaults
app: !Format "redis-{deploy_stage}"
deployment_name: !Format "redis-deployment-{deploy_stage}"
volume_claim_name: !Format "efs-{deploy_stage}"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: !Var deployment_name
spec:
  selector:
    matchLabels:
      app: !Var app
  serviceName: !Var app
  replicas: 1
  template:
    metadata:
      labels:
        app: !Var app
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
          claimName: !Var volume_claim_name
      containers:
      - name: redis
        image: redis:6
        # https://redis.io/topics/persistence
        args: ["--appendonly", "yes"]
        ports:
        - containerPort: 6379
        # defining the requests & limits equal to each other guarantees the pod will have a Quality of Service (QoS) of "Guaranteed"
        # https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/
        resources:
          requests:
            memory: "100M"
            cpu: "100m"
          limits:
            memory: "100M"
            cpu: "100m"
        volumeMounts:
        - mountPath: "/data"
          name: cwwed-volume-storage
          subPath: redis
