!Defaults
app: !Format "rabbitmq-{deploy_stage}"
deployment_name: !Format "rabbitmq-deployment-{deploy_stage}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: !Var deployment_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: !Var app
  template:
    metadata:
      labels:
        app: !Var app
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        ports:
        - containerPort: 5672
