!Defaults
image: !Format "flackdl/cwwed:{tag}"
secret_name: !Format "cwwed-secrets-{deploy_stage}"
app: !Format "cwwed-{deploy_stage}"
deployment_name: !Format "celery-deployment-{deploy_stage}"
volume_claim_name: !Format "efs-{deploy_stage}"
rabbitmq_service: !Format "rabbitmq-{deploy_stage}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: !Var deployment_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: !Var app
  template:
    metadata:
      labels:
        app: !Var app
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: !Var volume_claim_name
      containers:
      - name: celery
        image: !Var image
        imagePullPolicy: Always
        command: ['celery']
        args: ['worker', '--concurrency=10', '-A', 'cwwed', '-l', 'info']
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        resources:
          requests:
            memory: "1500M"
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          - name: DEPLOY_STAGE
            value: !Var deploy_stage
          - name: CELERY_BROKER
            value: !Var rabbitmq_service
          - name: CELERY_BACKEND
            value: !Var rabbitmq_service
        # secrets
        envFrom:
          - secretRef:
              name: !Var secret_name
