!Defaults
image: !Format "flackdl/cwwed:{tag}"
secret_name: !Format "cwwed-secrets-{deploy_stage}"
app: !Format "celery-{deploy_stage}"
deployment_name: !Format "celery-deployment-{deploy_stage}"
volume_claim_name: !Format "efs-{deploy_stage}"
redis_service: !Format "redis-{deploy_stage}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: !Var deployment_name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: !Var app
  template:
    metadata:
      labels:
        app: !Var app
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: !Var volume_claim_name
      containers:
      - name: celery
        image: !Var image
        imagePullPolicy: Always
        command: ['celery']
        # TODO - manually specify broker until I find out why celery is not using the configured broker
        args: ['--app', 'cwwed', '--broker', 'redis://redis-alpha', 'worker', '--loglevel', 'info']
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        resources:
          requests:
            memory: "1500M"
            cpu: "200m"
          limits:
            # kubernetes will throttle beyond this value
            cpu: "1"
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          - name: DEPLOY_STAGE
            value: !Var deploy_stage
          - name: CELERY_BROKER
            value: !Var redis_service
        # secrets
        envFrom:
          - secretRef:
              name: !Var secret_name
        # probes
        startupProbe:
          exec:
            command:
              - celery
              - -A
              - cwwed
              - -b
              # TODO - manually specify broker until I find out why celery is not using the configured broker
              - redis://redis-alpha
              - inspect
              - ping
          periodSeconds: 10
          failureThreshold: 30
          initialDelaySeconds: 30
        livenessProbe:
          exec:
            command:
              - celery
              - -A
              - cwwed
              - -b
              # TODO - manually specify broker until I find out why celery is not using the configured broker
              - redis://redis-alpha
              - inspect
              - ping
          periodSeconds: 60
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - celery
              - -A
              - cwwed
              - -b
              # TODO - manually specify broker until I find out why celery is not using the configured broker
              - redis://redis-alpha
              - inspect
              - ping
          periodSeconds: 60
          failureThreshold: 5
