!Defaults
image: !Format "flackdl/cwwed:{tag}"
secret_name: !Format "cwwed-secrets-{deploy_stage}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-container
  template:
    metadata:
      labels:
        app: celery-container
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: efs
      containers:
      - name: celery-container
        image: !Var image
        imagePullPolicy: Always
        command: ['celery']
        args: ['worker', '--concurrency=10', '-A', 'cwwed', '-l', 'info']
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        resources:
          requests:
            memory: "2000M"
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          - name: DEPLOY_STAGE
            value: !Var deploy_stage
          - name: CELERY_BROKER
            value: rabbitmq-service
          - name: CELERY_BACKEND
            value: rabbitmq-service
        # secrets
        envFrom:
          - secretRef:
              name: !Var secret_name
