apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwwed-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cwwed-container
  template:
    metadata:
      labels:
        app: cwwed-container
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
        # minikube
        #claimName: cwwed-volume-claim
         claimName: efs
      containers:
      - name: cwwed-container
        image: flackdl/cwwed
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          - name: DEPLOY_STAGE
            value: prod
          - name: CELERY_BROKER
            value: rabbitmq-service
          - name: CELERY_BACKEND
            value: rabbitmq-service
          - name: THREDDS_HOST
            value: thredds-service
          # secrets
          - name: DATABASE_URL
            # minikube
            #value: postgis://postgres@postgis-service:5432/postgres
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: DATABASE_URL
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SLACK_BOT_TOKEN
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SECRET_KEY
          - name: CWWED_NSEM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CWWED_NSEM_PASSWORD
          - name: CWWED_ARCHIVES_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CWWED_ARCHIVES_ACCESS_KEY_ID
          - name: CWWED_ARCHIVES_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CWWED_ARCHIVES_SECRET_ACCESS_KEY
          - name: EMAIL_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: EMAIL_HOST_PASSWORD
