apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-container
  template:
    metadata:
      labels:
        app: celery-container
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
        # minikube
        #claimName: cwwed-volume-claim
         claimName: efs
      containers:
      - name: celery-container
        image: flackdl/cwwed:kubernetes
        imagePullPolicy: Always
        command: ['celery']
        args: ['worker', '--concurrency=20', '-A', 'cwwed', '-l', 'info']
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings_aws
          - name: AWS_STORAGE_BUCKET_NAME
            value: cwwed-static-assets
          - name: CELERY_BROKER
            value: rabbitmq-service
          - name: CELERY_BACKEND
            value: rabbitmq-service
          # secrets
          - name: DATABASE_URL
            # minikube
            #value: postgis://postgres@postgis-service:5432/postgres
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: DATABASE_URL
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SLACK_BOT_TOKEN
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SECRET_KEY
