!Defaults
image: !Format "flackdl/cwwed:{tag}"
secret_name: !Format "cwwed-secrets-{deploy_stage}"
app: !Format "celery-{deploy_stage}-{queues}"
deployment_name: !Format "celery-{deploy_stage}-{queues}"
volume_claim_name: !Format "efs-{deploy_stage}"
redis_service: !Format "redis-{deploy_stage}"
request_cpu: "100m"
request_memory: "200M"
concurrency: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: !Var deployment_name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: !Var app
  template:
    metadata:
      labels:
        app: !Var app
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: !Var volume_claim_name
      containers:
      - name: celery
        image: !Var image
        imagePullPolicy: Always
        command: ['celery']
        args:
          - -A
          - cwwed
          - worker
          - --concurrency
          - !Var concurrency
          - --loglevel
          - info
          - --queues
          - !Var queues
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        resources:
          requests:
            memory: !Var request_memory
            cpu: !Var request_cpu
          limits:
            # kubernetes will throttle beyond this value
            cpu: "800m"
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          - name: DEPLOY_STAGE
            value: !Var deploy_stage
          - name: CELERY_BROKER
            value: !Var redis_service
        # secrets
        envFrom:
          - secretRef:
              name: !Var secret_name
        # probes
        startupProbe:
          exec:
            command:
              - celery
              - -A
              - cwwed
              - inspect
              - ping
          periodSeconds: 10
          failureThreshold: 30
          initialDelaySeconds: 30
        livenessProbe:
          exec:
            command:
              - celery
              - -A
              - cwwed
              - inspect
              - ping
          periodSeconds: 60
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - celery
              - -A
              - cwwed
              - inspect
              - ping
          periodSeconds: 60
          failureThreshold: 5
