!Defaults
app: !Format "redis-{deploy_stage}"
deployment_name: !Format "redis-deployment-{deploy_stage}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: !Var deployment_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: !Var app
  template:
    metadata:
      labels:
        app: !Var app
    spec:
      containers:
      - name: redis
        image: redis:5
        ports:
        - containerPort: 6379
