apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-flower-container
  template:
    metadata:
      labels:
        app: celery-flower-container
    spec:
      containers:
      - name: celery-flower-container
        image: flackdl/cwwed:kubernetes
        imagePullPolicy: IfNotPresent
        command: ['celery']
        args: ['flower', '-A', 'cwwed', '--port=5555', '--broker=amqp://guest:guest@rabbitmq-service:5672']
        ports:
        - containerPort: 5555
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings_aws
          - name: AWS_STORAGE_BUCKET_NAME
            value: cwwed-static-assets
          # secrets
          - name: DATABASE_URL
            # minikube
            #value: postgis://postgres@postgis-service:5432/postgres
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: DATABASE_URL
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SLACK_BOT_TOKEN
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SECRET_KEY
