apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-flower-container
  template:
    metadata:
      labels:
        app: celery-flower-container
    spec:
      containers:
      - name: celery-flower-container
        image: flackdl/cwwed
        imagePullPolicy: Always
        command: ['celery']
        args: ['flower', '-A', 'cwwed', '--basic_auth=$(CELERY_FLOWER_USER):$(CELERY_FLOWER_PASSWORD)', '--port=5555', '--broker=amqp://guest:guest@rabbitmq-service:5672']
        ports:
        - containerPort: 5555
        resources:
          requests:
            memory: "500M"
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          # secrets
          - name: DATABASE_URL
            # minikube
            #value: postgis://postgres@postgis-service:5432/postgres
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: DATABASE_URL
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SLACK_BOT_TOKEN
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SECRET_KEY
          - name: CWWED_ARCHIVES_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CWWED_ARCHIVES_ACCESS_KEY_ID
          - name: CWWED_ARCHIVES_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CWWED_ARCHIVES_SECRET_ACCESS_KEY
          - name: CELERY_FLOWER_USER
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CELERY_FLOWER_USER
          - name: CELERY_FLOWER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: CELERY_FLOWER_PASSWORD
