!Defaults
app: !Format "opendap-{deploy_stage}"
deployment_name: !Format "opendap-deployment-{deploy_stage}"
volume_claim_name: !Format "efs-{deploy_stage}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: !Var deployment_name
  labels:
    app: !Var app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: !Var app
  template:
    metadata:
      labels:
        app: !Var app
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: !Var volume_claim_name
      containers:
      - name: opendap
        image: opendap/hyrax:1.15.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/usr/share/hyrax"
          name: cwwed-volume-storage
          subPath: OPENDAP
          readOnly: true
        resources:
          requests:
            memory: "750M"
