apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwwed-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cwwed-container
  template:
    metadata:
      labels:
        app: cwwed-container
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
        # minikube
        #claimName: cwwed-volume-claim
         claimName: efs
      containers:
      - name: cwwed-container
        image: flackdl/cwwed
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          - name: DEPLOY_STAGE
            value: prod
          - name: CELERY_BROKER
            value: rabbitmq-service
          - name: CELERY_BACKEND
            value: rabbitmq-service
          - name: THREDDS_HOST
            value: opendap-service
        # secrets
        envFrom:
          - secretRef:
              name: cwwed-secrets
