apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-next-upstream: error timeout http_502
spec:
  rules:
  - host: alpha.cwwed-staging.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cwwed-alpha
          servicePort: 80
  - host: dev.cwwed-staging.com
    http:
      paths:
        - path: /
          backend:
            # TODO - update back to a true "dev" version whenever appropriate
            serviceName: cwwed-alpha
            servicePort: 80
---
