apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-alpha
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: alpha.cwwed-staging.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cwwed
          servicePort: 80
---
