!Defaults
image: !Format "flackdl/cwwed:{tag}"
secret_name: !Format "cwwed-secrets-{deploy_stage}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cwwed-job-covered-data
spec:
  backoffLimit: 2  # number of retries
  template:
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: efs
      # https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#handling-pod-and-container-failures
      restartPolicy: Never  # don't restart the container if the entire process fails
      containers:
      - name: cwwed-covered-data
        image: !Var image
        command: ['python']
        args: ['manage.py', 'collect_covered_data']
        # args: ['manage.py', 'collect_covered_data', '--storm_id', '1', '--covered_data_id', '9']
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings
          - name: DEPLOY_STAGE
            value: !Var deploy_stage
          - name: CELERY_BROKER
            value: rabbitmq-service
          - name: CELERY_BACKEND
            value: rabbitmq-service
        # secrets
        envFrom:
          - secretRef:
              name: !Var secret_name
