#apiVersion: batch/v1beta1
apiVersion: batch/v1
#kind: CronJob
kind: Job
metadata:
  name: cwwed-container-covered-data
spec:
  # once a day, early morning, east coast
  #schedule: "8 * * * *"
  #jobTemplate:
  #spec:
  template:
    spec:
      volumes:
      - name: cwwed-volume-storage
        persistentVolumeClaim:
         claimName: efs
      restartPolicy: OnFailure
      containers:
      - name: cwwed-container-covered-data
        image: flackdl/cwwed:s3
        command: ['python']
        args: ['manage.py', 'collect_covered_data']
        volumeMounts:
        - mountPath: "/media/bucket/cwwed"
          name: cwwed-volume-storage
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: cwwed.settings_aws
          - name: AWS_STORAGE_BUCKET_NAME
            value: cwwed-static-assets
          - name: CELERY_BROKER
            value: rabbitmq-service
          - name: CELERY_BACKEND
            value: rabbitmq-service
          # secrets
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: DATABASE_URL
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SLACK_BOT_TOKEN
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cwwed-secrets
                key: SECRET_KEY
