kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgis-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgis"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgis-volume-claim
spec:
  storageClassName: ""
  volumeName: postgis-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
