kind: PersistentVolume
apiVersion: v1
metadata:
  name: cwwed-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/bucket/cwwed"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cwwed-volume-claim
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
