kind: PersistentVolume
apiVersion: v1
metadata:
  name: cwwed-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/cwwed"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cwwed-volume-claim
spec:
  storageClassName: ""
  volumeName: cwwed-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
