!Defaults
name: !Format "opendap-{deploy_stage}"
---
kind: Service
apiVersion: v1
metadata:
  name: !Var name
spec:
  selector:
    app: !Var name
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 8080
