!Defaults
app: !Format "redis-{deploy_stage}"
name: !Format "redis-{deploy_stage}"
---
kind: Service
apiVersion: v1
metadata:
  name: !Var name
spec:
  selector:
    app: !Var app
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
