---
apiVersion: v1
kind: Service
metadata:
  name: celery-flower-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  flower_mapping
      prefix: /
      service: celery-flower-service
spec:
  selector:
    app: celery-flower-container
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
