---
apiVersion: v1
kind: Service
metadata:
  name: cwwed-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  cwwed_mapping
      prefix: /
      service: cwwed-service
spec:
  selector:
    app: cwwed-container
  ports:
    - port: 80
      targetPort: 80
